# Generated by Django 4.2.1 on 2023-05-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='수집된 뉴스의 제목', max_length=255)),
                ('link', models.CharField(help_text='수집된 뉴스의 하이퍼링크', max_length=1000)),
                ('link_hash', models.CharField(help_text='수집된 뉴스의 고유 해시값', max_length=100)),
                ('keyword', models.CharField(help_text='수집에 사용된 키워드', max_length=100)),
                ('vendor', models.CharField(help_text='뉴스 정보의 제공자 정보', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='뉴스 수집 일시')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='뉴스 수집 정보 변경 일시')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterQueues',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(help_text='수집 요청 키워드', max_length=255)),
                ('status', models.CharField(help_text='상태 - 요청: requested, 처리중: processing, 완료: completed, 실패: failed', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='수집 요청 일시')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수집 요청 변경 일시')),
            ],
        ),
    ]
